### ISSUE TITLE
Description edit

### ISSUE THREAD

**Issue by dkouvdis** [eroak/rpi-433#5]
Hi.

Why your description is "Raspberry Pi 2", it should work for any model?

Thanks

**Comment by eroak** [comment]
Hi djouvdis,

Because I have a Raspberry Pi 2 and i don't know if rpi-433 is working on others models. Could you tell me if this is working on other models ?

Thanks

**Comment by FlorianWendelborn** [comment]
@eroak didn't test this completely, but I can confirm that it (at least) works for some GPIO pins on my RPi 3.

**Comment by eroak** [comment]
Great ! Thanks for your feedback !

**Comment by PJCzx** [comment]
I'm currently testing on RPI2 B. Here is my `gpio readall` output
`
 +-----+-----+---------+------+---+-Model B2-+---+------+---------+-----+-----+
 | BCM | wPi |   Name  | Mode | V | Physical | V | Mode | Name    | wPi | BCM |
 +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
 |     |     |    3.3v |      |   |  1 || 2  |   |      | 5v      |     |     |
 |   2 |   8 |   SDA.1 |   IN | 1 |  3 || 4  |   |      | 5V      |     |     |
 |   3 |   9 |   SCL.1 |   IN | 1 |  5 || 6  |   |      | 0v      |     |     |
 |   4 |   7 | GPIO. 7 |   IN | 1 |  7 || 8  | 1 | ALT0 | TxD     | 15  | 14  |
 |     |     |      0v |      |   |  9 || 10 | 1 | ALT0 | RxD     | 16  | 15  |
 |  17 |   0 | GPIO. 0 |   IN | 0 | 11 || 12 | 0 | IN   | GPIO. 1 | 1   | 18  |
 |  27 |   2 | GPIO. 2 |   IN | 0 | 13 || 14 |   |      | 0v      |     |     |
 |  22 |   3 | GPIO. 3 |  OUT | 0 | 15 || 16 | 1 | OUT  | GPIO. 4 | 4   | 23  |
 |     |     |    3.3v |      |   | 17 || 18 | 0 | IN   | GPIO. 5 | 5   | 24  |
 |  10 |  12 |    MOSI |   IN | 0 | 19 || 20 |   |      | 0v      |     |     |
 |   9 |  13 |    MISO |   IN | 0 | 21 || 22 | 0 | IN   | GPIO. 6 | 6   | 25  |
 |  11 |  14 |    SCLK |   IN | 0 | 23 || 24 | 1 | IN   | CE0     | 10  | 8   |
 |     |     |      0v |      |   | 25 || 26 | 0 | OUT  | CE1     | 11  | 7   |
 +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
 |  28 |  17 | GPIO.17 |   IN | 0 | 51 || 52 | 0 | IN   | GPIO.18 | 18  | 29  |
 |  30 |  19 | GPIO.19 |   IN | 0 | 53 || 54 | 0 | OUT  | GPIO.20 | 20  | 31  |
 +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
 | BCM | wPi |   Name  | Mode | V | Physical | V | Mode | Name    | wPi | BCM |
 +-----+-----+---------+------+---+-Model B2-+---+------+---------+-----+-----+
`
Because I use several other GPIO, I plugged two brand new Rx/Tx from the same bag like this:
Transmitter:
- VCC: Physical 2 (5V)
- GND: Physical 25 (0v)
- Txd: Physical 26 (wPi 11)

Receiver:
- VCC: Physical 4 (5V for 3,5V to 12V)
- GND: Physical 6 (0v)
- Rxd: Physical 11 (wPi 0)

![img_6726](https://cloud.githubusercontent.com/assets/2682199/15192797/104eb612-17bb-11e6-9b9b-aba76577a473.JPG)

I then execute this code as sudo user `sudo node exemple.js`

`var rpi433    = require('rpi-433'),
    rfSniffer = rpi433.sniffer(0, 500), 
    rfSend    = rpi433.sendCode;
 
// Receive
rfSniffer.on('codes', function (code) {
  console.log('Code received: ', code);
});

// Send
rfSend(1234, 11, function(error, stdout) {   
  if(!error) console.log("Sending:", stdout);                       
});`

And a get only this output:
`Sending: 1234`

I tried with and without antenna. Does any one of you have an idea if the RPI version can be the reason it's not working? I can't see what's wrong it my code.

Thx for your help
